spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/walletscheduler?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 123456789

  jpa:
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
